"""add timestamp to Image table

Revision ID: 22f82d8a4f50
Revises: 43ccb588feb2
Create Date: 2020-06-21 23:19:30.897172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f82d8a4f50'
down_revision = '43ccb588feb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_image_timestamp'), 'image', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_timestamp'), table_name='image')
    op.drop_column('image', 'timestamp')
    # ### end Alembic commands ###
